'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ALevelChess.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueBoardPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueBoardPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Castle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Castle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DefaultSkin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultSkin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenBoardPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenBoardPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Locked8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PinkBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PinkBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PinkBoardPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PinkBoardPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedBoardPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedBoardPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Selection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Selection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1BishopB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1BishopB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1BishopW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1BishopW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1KingB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1KingB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1KingW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1KingW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1KnightB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1KnightB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1KnightW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1KnightW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1PawnB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1PawnB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1PawnW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1PawnW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1QueenB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1QueenB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1QueenW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1QueenW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1RookB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1RookB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set1RookW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set1RookW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2BishopB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2BishopB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2BishopW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2BishopW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2KingB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2KingB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2KingW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2KingW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2KnightB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2KnightB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2KnightW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2KnightW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2PawnB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2PawnB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2PawnW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2PawnW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2QueenB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2QueenB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2QueenW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2QueenW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2RookB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2RookB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set2RookW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set2RookW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3BishopB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3BishopB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3BishopW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3BishopW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3KingB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3KingB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3KingW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3KingW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3KnightB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3KnightB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3KnightW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3KnightW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3PawnB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3PawnB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3PawnW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3PawnW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3QueenB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3QueenB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3QueenW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3QueenW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3RookB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3RookB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Set3RookW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Set3RookW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Class GameForm1
        '''    &apos;Chess pieces:
        '''    &apos;1) Pawn
        '''    &apos;2) Bishop
        '''    &apos;3) Rook
        '''    &apos;4) Knight
        '''    &apos;5) Queen
        '''    &apos;6) King
        '''
        '''    Public pb(7, 7) As PictureBox
        '''    Public whiteking As King
        '''    Public whitequeen As Queen
        '''    Public whitebishop(1) As Bishop
        '''    Public whiteknight(1) As Knight
        '''    Public whitepawn(7) As Pawn
        '''    Public whiterook(1) As Rook
        '''    Public blackking As King
        '''    Public blackqueen As Queen
        '''    Public blackbishop(1) As Bishop
        '''    Public blackknight(1) As Knight
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpdatedNEA() As String
            Get
                Return ResourceManager.GetString("UpdatedNEA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VMove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VMove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowBoardPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowBoardPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
